// Common symbol -> CoinGecko id overrides for ambiguous symbols
export default {
  btc: 'bitcoin',
  eth: 'ethereum',
  usdt: 'tether',
  usdc: 'usd-coin',
  bnb: 'binancecoin',
  ada: 'cardano',
  xrp: 'ripple',
  sol: 'solana',
  doge: 'dogecoin',
  matic: 'polygon',
  ltc: 'litecoin',
  dot: 'polkadot',
  avax: 'avalanche-2',
  link: 'chainlink',
  shib: 'shiba-inu',
  uni: 'uniswap',
  atom: 'cosmos',
  xlm: 'stellar',
  near: 'near',
  apt: 'aptos',
  arb: 'arbitrum',
  op: 'optimism',
  fil: 'filecoin',
  hbar: 'hedera-hashgraph',
  vet: 'vechain',
  algo: 'algorand',
  ftm: 'fantom',
  sand: 'the-sandbox',
  mana: 'decentraland',
  aave: 'aave',
  mkr: 'maker',
  crv: 'curve-dao-token',
  trx: 'tron',
  dai: 'dai',
  wbtc: 'wrapped-bitcoin',
  etc: 'ethereum-classic',
  bch: 'bitcoin-cash',
  // Ensure correct mappings
  bitcoin: 'bitcoin',
  ethereum: 'ethereum',
  binancecoin: 'binancecoin',
};